import Copyright from '../components/Copyright'

const PoliticaPrivacidade = () => {
    return (
        <>
            <div className="home-container">
                <div className='p-10'>
                    <h2 className='h2-bold text-center pb-8'>Politica de Privacidade</h2>
                    <p className='text-justify'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in lorem libero. Maecenas consectetur magna in nibh pellentesque aliquet. Pellentesque nec ligula quis urna lobortis bibendum. Phasellus ac lectus venenatis, facilisis velit aliquet, viverra orci. Nam sagittis pulvinar dolor, gravida sagittis tortor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur volutpat eros nec quam luctus fringilla. Nam imperdiet, dui ut placerat tincidunt, odio turpis ornare nisl, non bibendum diam odio non est. Donec consectetur posuere metus, vitae fermentum sem fringilla sit amet. Donec dignissim et ligula nec imperdiet. Vivamus auctor, neque sit amet maximus mollis, mauris tortor scelerisque orci, vitae fermentum sapien odio sed lectus. Duis neque eros, consequat et sem ornare, convallis accumsan felis. Fusce gravida auctor posuere.

                        Nam vel lobortis augue. Integer libero mauris, eleifend quis placerat non, lacinia sed odio. Nunc mollis interdum tincidunt. Sed mauris lectus, blandit sit amet nisl a, mollis malesuada enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In porttitor mattis dui, nec lacinia leo pellentesque eget. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla vehicula mi quis enim dignissim volutpat. Nunc lacinia tempus libero sed bibendum. Suspendisse potenti. Nam at neque velit. Nam quis risus ac lectus aliquam euismod a vel nisi. Praesent aliquet vitae sem ac molestie.

                        Phasellus nec facilisis tortor. Proin at facilisis velit. Pellentesque tristique magna sem, sed mollis eros posuere suscipit. Aenean dolor sem, vestibulum ut posuere sit amet, dapibus nec massa. Quisque commodo ornare porttitor. Suspendisse eu auctor eros. Vestibulum hendrerit enim a enim aliquam, non sagittis orci egestas. Cras nec fermentum ex, sed rhoncus risus. Vestibulum eget enim vel nisl sollicitudin semper. Quisque eget libero id ipsum placerat egestas ut vitae erat. In tincidunt sollicitudin odio, a tincidunt ipsum rutrum at. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus quis feugiat magna. Aliquam tristique maximus volutpat.

                        Sed eu nunc aliquet, pellentesque mauris sit amet, placerat sapien. Curabitur convallis gravida rutrum. Fusce aliquet nunc vel eros facilisis, in consequat augue mattis. Nam tempor feugiat sem a ullamcorper. Aliquam at neque velit. Donec et malesuada mi. Maecenas quis libero faucibus, sollicitudin odio ut, luctus urna. Praesent libero lorem, elementum sit amet vestibulum vel, maximus sit amet ligula. Donec consequat quam et ornare dignissim. Ut sagittis, nisl sit amet pretium porttitor, mauris est elementum sapien, sit amet elementum nibh enim eget diam.

                        Proin est libero, efficitur id tortor eget, tincidunt condimentum justo. Etiam accumsan sodales ex, ac facilisis est dictum nec. Pellentesque vitae tincidunt lorem. Pellentesque sapien quam, molestie a pretium in, ornare nec odio. Fusce tempor aliquam dui. Mauris non elementum diam, ut hendrerit nunc. Nulla facilisi. Etiam bibendum, quam accumsan fringilla mattis, nunc nulla aliquam eros, et posuere ex velit ut nisl.

                        Donec pretium magna eu neque fermentum, in facilisis enim ullamcorper. Cras scelerisque scelerisque mi vitae consectetur. Proin quis mattis enim, laoreet fringilla quam. Pellentesque eget dictum neque. Quisque eleifend elit quis posuere sodales. Phasellus in nibh ante. Donec elementum sem sed pretium eleifend. Integer vulputate eu justo ullamcorper dapibus. Vivamus pulvinar odio a mauris ornare, nec tempus nulla maximus. Sed elementum turpis id urna vehicula, ut accumsan nisl consectetur. Donec ultricies vulputate mi, non molestie augue commodo vel. Curabitur ornare, orci sed tincidunt suscipit, urna enim volutpat lorem, iaculis lacinia leo nunc ac elit.

                        Morbi posuere bibendum nibh eget mollis. Nulla eleifend pulvinar libero pharetra faucibus. Vivamus sit amet maximus lacus, pulvinar lacinia libero. Sed ipsum felis, accumsan quis metus nec, molestie ultrices lacus. Donec quis urna at nisi faucibus tristique. In sed neque rhoncus, ornare dolor eu, iaculis magna. Proin sodales facilisis sem in ultrices. Donec iaculis turpis sit amet lorem venenatis vulputate. Nam volutpat diam lacus, vitae euismod sem maximus in. Suspendisse eget eros ut sapien facilisis auctor. Donec non aliquet dui, quis pharetra leo. Etiam et quam in ante venenatis viverra sed non orci. Aliquam fringilla, nibh quis tempus feugiat, dui nulla rutrum tellus, non congue neque augue et mauris.

                        Nullam id ipsum aliquet, elementum neque quis, accumsan lacus. Maecenas et pellentesque nisl. Donec mi est, ultricies quis est sed, vehicula tincidunt diam. Nulla efficitur placerat ex, ut auctor massa aliquet sed. Aenean eget augue id enim dapibus ornare ullamcorper a leo. In id finibus justo, sed eleifend turpis. Sed ipsum arcu, dignissim et tempus eu, mollis a quam. Duis pretium accumsan sollicitudin. Ut tincidunt semper commodo. Maecenas non diam neque. Duis eget ante sed quam faucibus volutpat id quis dolor. Donec finibus consequat urna, et semper ipsum tempus id. Morbi euismod in magna non consectetur. Ut sed molestie libero, nec consequat ante. Duis malesuada mollis dui non volutpat. Duis vulputate lacinia tincidunt.

                        Cras id quam non lacus congue mollis. Praesent ac mi sed lorem rhoncus luctus. Nullam et ante sit amet ipsum semper mollis in vitae enim. Proin mattis egestas lacus, ac ultrices lectus pulvinar iaculis. Suspendisse enim enim, pulvinar nec magna vitae, porttitor sollicitudin enim. Curabitur a tincidunt purus, eget rutrum sapien. Mauris et gravida nisl, nec dignissim mi. Cras ut nibh in magna pretium eleifend. Donec nulla nunc, euismod eu lacinia sit amet, egestas ac lacus. Pellentesque tempus felis varius ornare tempor. Pellentesque auctor placerat risus eu pretium. Cras lacinia elit eget ligula laoreet mollis. Morbi non dui eu quam dictum semper. Duis ut scelerisque libero.

                        Donec sagittis facilisis maximus. Donec ac nisl eget sem faucibus volutpat ut vitae orci. Nullam quis rutrum ligula. Vestibulum ullamcorper neque nec tortor pellentesque, sit amet congue ante faucibus. Vestibulum facilisis risus at lacus gravida, vel pretium nisl congue. Sed eget dignissim tortor. Sed convallis tristique magna, nec sollicitudin nunc. Phasellus ut eleifend tortor. Suspendisse id orci ac orci tempor sodales a nec turpis. Nam molestie nisl in commodo sollicitudin. Nulla id maximus est. Vestibulum blandit varius tortor eu semper. Proin feugiat viverra mauris a tincidunt. Donec congue vel augue non ullamcorper. In maximus, nibh at vehicula tempus, eros mi sodales eros, ac accumsan lorem metus at tellus. Quisque vulputate ullamcorper nulla, in volutpat nunc euismod vel.

                        Praesent rutrum feugiat tortor, at sollicitudin augue porttitor at. Vestibulum id diam sapien. Pellentesque a pulvinar libero. Sed id laoreet elit, ac tristique felis. Praesent id nisi turpis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam vestibulum ac ligula eget fringilla. Sed eu pulvinar mi, quis sodales nisi. Sed tempus ut sem imperdiet cursus. Curabitur scelerisque, nisi a faucibus convallis, lectus nisi viverra tellus, a posuere leo purus ac purus.

                        Quisque id mi risus. Sed pretium nisi a purus ornare interdum. Curabitur posuere lorem tellus, quis placerat nulla gravida rutrum. In ac nisl urna. Morbi tristique ante et dictum rhoncus. In hac habitasse platea dictumst. Nulla cursus elit a arcu imperdiet, non vehicula nulla porttitor.</p>
                </div>
            </div>
            <Copyright />
        </>
    )
}

export default PoliticaPrivacidade